# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19e7cdf4b53ded7c86340c3218703f9e91fa4b024855be863056ddcf51902772a9d6dbe318c78e467472563f45936745709e0088b78c33c363fb33539617de0c

test:
  secret_key_base: 85d7218d0a2d180636fb05718eea452fa6f900ddaccda0dc26ce9c63f16d62440f0655dc39c75c56c86644b806897d452980ed8b23d3da033e5fa0614d47b99d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
